const topics: Record<string, string[]> = {
  "": [
    "§6TauUI Help §7- Available topics:",
    "§e/tau help commands §7- List all commands",
    "§e/tau help shop §7- Shop system guide",
    "§e/tau help sidebar §7- Sidebar system guide",
    "§e/tau help menus §7- Menu/form system guide",
    "§e/tau help bindings §7- Item/entity binding guide",
    "§e/tau help ranks §7- Rank & chat formatting",
    "§e/tau help stats §7- Player stats & profiles",
    "§e/tau help social §7- TPA, homes, pay, settings",
    "§e/tau help teams §7- Team system",
    "§e/tau help warps §7- Server warps",
    "§e/tau help plots §7- Plot system",
    "§e/tau help generators §7- Generator system",
    "§e/tau help crates §7- Crate system",
    "§e/tau help items §7- Custom Tau items",
    "§e/tau help lootchests §7- Loot chest system",
    "§e/tau help commandbuilder §7- Command builder system",
    "§e/tau help prune §7- Data pruning",
    "§e/tau help areas §7- Custom areas",
    "§e/tau help placeholders §7- Available placeholders",
    "§7Use §e/tau help <topic>§7 for details.",
  ],
  commands: [
    "§6--- Commands ---",
    "§e/tau:open <menu_id> §7- Open a saved menu",
    "§e/tau:shop <profile> §7- Open a shop profile",
    "§e/tau:myshop §7- Manage your player-run shop",
    "§e/tau:market §7- Browse public player listings",
    "§e/tau:shopadmin §7- Player shop admin settings (op)",
    "§e/tau:shopclaim §7- Claim offline player-shop earnings",
    "§e/tau:config §7- Open feature config (op)",
    "§e/tau:creator §7- Open admin UI creator (op)",
    "§e/tau:sidebar §7- Open sidebar editor (op)",
    "§e/tau:warp [name] §7- Teleport to warp or open menu",
    "§e/tau:warps §7- Open warp list",
    "§e/tau:warpsadmin §7- Open warp admin menu (op)",
    "§e/tau:plot §7- Open your plot info/teleport menu",
    "§e/tau:plots §7- Open plot admin menu (op)",
    "§e/tau:generatorsadmin §7- Open generator admin (op)",
    "§e/tau:crate §7- Open crate admin (op)",
    "§e/tau:item §7- Open TauItems admin (op)",
    "§e/tau:lootchests §7- Open loot chest admin (op)",
    "§e/tau:rank §7- Open rank manager (op)",
    "§e/tau:profile §7- Open profile browser",
    "§e/tau:stats §7- View or edit stats",
    "§e/tau:richest §7- View richest players",
    "§e/tau:help [topic] §7- Show this help",
    "§e/tau:cleardata §7- Wipe all Tau data (op)",
    "§e/tau:debugscore <obj> §7- Debug scoreboard score",
    "§e/tau:credits §7- Show credits",
  ],
  shop: [
    "§6--- Shop System ---",
    "§e1.§7 Create a shop profile in §e/tau:creator§7 → Player Systems → Shop Profiles",
    "§e2.§7 Set the §ecurrency objective§7 (e.g. money)",
    "§e3.§7 Add items with §ebuy/sell prices§7 and quantities",
    "§e4.§7 Open the shop: §e/tau:shop <profile_id>",
    "§e5.§7 Bind to a menu button: §eshop transaction§7 action",
    "§7Value format: §e<profile>|key:<item_key>§7 or §ekey:<item_key>§7",
    "§7Player shops: §e/tau:myshop§7 and §e/tau:market§7 (escrow custom items).",
  ],
  warps: [
    "§6--- Warps ---",
    "§e/tau:warps §7- Open the warp list",
    "§e/tau:warp <name> §7- Teleport to a warp",
    "§e/tau:warpsadmin §7- Manage warps (op)",
    "§7Features: cross-dimension, categories, admin-managed.",
    "§7Admin: create at your position, set location, delete.",
  ],
  plots: [
    "§6--- Plots ---",
    "§e/tau:plot §7- Open your plot info/teleport menu",
    "§e/tau:plots §7- Open plot admin menu (op)",
    "§7Player: view plot info, teleport to your plot.",
    "§7Admin: set origin, size, spacing, count, auto-build.",
    "§7Auto-build: borders, floor, barrier roof.",
    "§7Team plots: owner holds the plot for the team.",
    "§7Snapshots save/restore player builds automatically.",
  ],
  generators: [
    "§6--- Generators ---",
    "§e/tau:generatorsadmin §7- Open generator admin (op)",
    "§7Or via §e/tau:creator§7 → World Systems → Generators",
    "§7Place a generator block to start generating items.",
    "§7Upgrade tiers to increase output rate (0 ticks = turbo).",
    "§7Weighted generators roll random blocks from an admin pool.",
    "§7Admin protected generators are view-only for normal players.",
    "§7Auto breakers can be purchased to auto-collect.",
    "§7Generators save with plot snapshots.",
  ],
  crates: [
    "§6--- Crates ---",
    "§e/tau:crate §7- Open crate admin (op)",
    "§7Or via §e/tau:creator§7 → World Systems → Crates",
    "§7Configure crate blocks, keys, rewards, and animations.",
    "§7Give keys to players and let them open at crate blocks.",
    "§7Supports item, score, and tag rewards with weights.",
  ],
  items: [
    "§6--- Custom Tau Items ---",
    "§e/tau:item §7- Open TauItems admin (op)",
    "§7Or via §e/tau:creator§7 → Admin / Rules → TauItems",
    "§7Create custom items with triggers (use, hit, mine).",
    "§7Bind commands, sounds, or effects to item usage.",
    "§7Supports costs (money, XP, health) and consumption modes.",
  ],
  commandbuilder: [
    "§6--- Command Builder ---",
    "§e/tau:creator§7 → Menu & UI Management → Command Builder",
    "§7Create custom triggered command chains with conditions and actions.",
    "§7Supports rank, tag, score, permission conditions.",
    "§7Actions: commands, effects, scores, tags, messages with delays.",
  ],
  lootchests: [
    "§6--- Loot Chests ---",
    "§e/tau:lootchests §7- Open loot chest admin (op)",
    "§7Or via §e/tau:creator§7 → World Systems → Loot Chests",
    "§7Configure pools, capture chest snapshots, bind locations.",
    "§7Supports weighted templates, refill intervals, and commands.",
  ],
  sidebar: [
    "§6--- Sidebar System ---",
    "§e1.§7 Open §e/tau:sidebar§7 (or creator → Player Systems → Sidebar Customizer)",
    "§e2.§7 Create a sidebar and set §eupdate interval§7 (ticks)",
    "§e3.§7 Add lines with §eplaceholders§7 like §e[name]§7 or §e[money]",
    "§e4.§7 Tag players §esidebar:<id>§7 to bind them",
    "§e5.§7 Set §epriority§7 for conflict resolution",
    "§7Placeholders: §e[name] [money] [health] [ping] [pos] [tps] [rank_tag]",
  ],
  menus: [
    "§6--- Menu / Form System ---",
    "§e1.§7 Create a form in §e/tau:creator",
    "§e2.§7 Choose §eAction Form§7 (buttons) or §eModal Form§7 (inputs)",
    "§e3.§7 Add elements and bind them to actions",
    "§eAction types:",
    "  §eCOMMAND_PLAYER§7 - Run command as player",
    "  §eCOMMAND_SUDO§7 - Run command as console",
    "  §eOPEN_MENU§7 - Open another menu",
    "  §eSHOP_TRANSACTION§7 - Buy/sell shop item",
    "  §eCLOSE§7 - Close the UI",
  ],
  bindings: [
    "§6--- Binding System ---",
    "§eItem binds:§7 Bind a menu to an item type id",
    "  Use creator → Menu & UI Management → Bindings → Set item bind",
    "§eLore binds:§7 Match menu by item lore text",
    "  Use creator → Menu & UI Management → Bindings → Set item lore bind",
    "§eEntity binds:§7 Tag NPCs with §emenuid:<id>",
    "  Or: Bindings → Set entity-tag bind",
    "§eScriptevent:§7 §e/scriptevent tau open <id>",
  ],
  ranks: [
    "§6--- Ranks & Chat Formatting ---",
    "§e/tau:config §7- Toggle ranks feature",
    "§e/tau:creator §7- Player Systems → Ranks (op)",
    "§7Each rank has: color, prefix, suffix, permissions, chat format.",
    "§7Chat placeholders: §e[name] [rank] [rank_prefix] [rank_suffix] [team] [money] [message]",
    "§7Default rank auto-assigned to new players.",
  ],
  stats: [
    "§6--- Stats & Profiles ---",
    "§e/tau:stats <player> [stat] [value] §7- View/edit stats (op)",
    "§7Tracked: kills, deaths, killstreak, blocks placed/broken,",
    "  time played, distance traveled.",
    "§7Profiles: customizable player info cards.",
    "§7Use §e/tau:profile §7or §e/tau:creator§7 → Player Systems to edit profile visibility.",
  ],
  social: [
    "§6--- Social Features ---",
    "§e/tau:tpa [player] §7- Open TPA menu or send a request",
    "§e/tau:tpaccept [id] §7- Accept oldest (or specific) TPA request",
    "§e/tau:tpdeny [id] §7- Deny oldest (or specific) TPA request",
    "§e/tau:tpacancel <id> §7- Cancel an outgoing TPA request",
    "§e/tau:sethome [name] §7- Set a named home",
    "§e/tau:home [name] §7- Teleport to a home",
    "§e/tau:delhome <name> §7- Delete a home",
    "§e/tau:homes §7- List your homes",
    "§e/tau:pay <player> <amount> §7- Pay another player",
    "§e/tau:settings §7- Open your social settings",
    "§7Player settings: allow TPA, allow pay, show messages.",
    "§7Admin: social settings in §e/tau:config§7.",
  ],
  teams: [
    "§6--- Teams ---",
    "§e/tau:team §7- Open team menu",
    "§e/tau:team create <name> §7- Create a team",
    "§e/tau:team join <name> §7- Join a team (invite-only)",
    "§e/tau:team leave §7- Leave your team",
    "§e/tau:team invite <player> §7- Invite a player (owner)",
    "§e/tau:team kick <player> §7- Kick a member (owner)",
    "§e/tau:team promote <player> §7- Promote a member to admin (owner)",
    "§e/tau:team demote <player> §7- Demote an admin to member (owner)",
    "§e/tau:team disband §7- Disband your team (owner)",
    "§7Features: friendly fire toggle, team plot toggle.",
    "§7Team plot: owner holds the plot, members share it.",
    "§7Roles: owner, admin, member. Admins can set/delete team homes.",
  ],
  teamHomes: [
    "§6--- Team Homes ---",
    "§e/tau:teamsethome [name] §7- Set a team home at your location (owner/admin)",
    "§e/tau:teamhome [name] §7- Teleport to a team home",
    "§e/tau:delteamhome <name> §7- Delete a team home (owner/admin)",
    "§e/tau:teamhomes §7- List your team's homes",
    "§7Manage from the team menu: §e/tau:team §7-> Team Homes.",
  ],
  prune: [
    "§6--- Data Pruning ---",
    "§e/tau:prune §7- Open prune menu (op)",
    "§e/tau:prune dry §7- Preview what would be removed",
    "§e/tau:prune run §7- Execute the prune",
    "§7Prune by category: stats, profiles, teams, plots,",
    "  homes, tpa, pay, player settings.",
    "§7Uses inactivity window (default 30 days).",
  ],
  placeholders: [
    "§6--- Available Placeholders ---",
    "§e[name] §7- Player name",
    "§e[rank] §7- Player rank with color",
    "§e[rank_prefix] §7- Rank prefix",
    "§e[rank_suffix] §7- Rank suffix",
    "§e[team] §7- Team tag (if in a team)",
    "§e[money] §7- Scoreboard currency",
    "§e[health] §7- Player health",
    "§e[health_color] §7- Red(<5) / Orange(<10) / Green",
    "§e[ping] §7- Network latency",
    "§e[pos] §7- X, Y, Z coordinates",
    "§e[tps] §7- Server tick rate",
    "§e[rank_tag] §7- Player rank (static)",
    "§e[message] §7- Chat message",
    "§7Use §e[placeholder]§7 in sidebar lines, chat format, or form values",
  ],
  areas: [
    "§6--- Custom Areas ---",
    "§7Custom areas let you define 3D regions with special rules.",
    "§7Configure them in §e/tau:creator§7 → World Systems → Custom Areas.",
    "§7Each area can have:",
    "§e  •§7 Enter/leave messages (chat or global)",
    "§e  •§7 Permission overrides: PvP, block break/place, item use, entity interact",
    "§e  •§7 Periodic effects (any potion effect on interval)",
    "§e  •§7 Periodic command rules (commands on interval per player)",
    "§e  •§7 Rank filters (who is affected)",
    "§e  •§7 Combat drop while tagged (2 second grace, then inventory drops)",
    "§e  •§7 Ticking area support (manual apply)",
    "§7Operators bypass custom-area block restrictions.",
  ],
};

export function getHelpLines(topicKey: string): string[] {
  return topics[topicKey] ?? topics[""];
}
