export const ICONS = {
    creator: "textures/items/book_normal",
    actionForm: "textures/items/paper",
    modalForm: "textures/items/book_writable",
    edit: "textures/items/iron_pickaxe",
    delete: "textures/items/redstone_dust",
    back: "textures/items/arrow",
    confirm: "textures/items/emerald",
    cancel: "textures/items/redstone_dust",
    shop: "textures/items/iron_ingot",
    buy: "textures/items/emerald",
    sell: "textures/items/gold_ingot",
    sellAll: "textures/items/diamond",
    settings: "textures/items/redstone_dust",
    binding: "textures/items/lead",
    command: "textures/items/repeater",
    menu: "textures/items/book_normal",
    sidebar: "textures/items/diamond",
    rank: "textures/items/nether_star",
    plot: "textures/items/spyglass",
    item: "textures/items/name_tag",
    utility: "textures/items/feather",
};
export const WORKING_ICON_OPTIONS = [
    { label: "None" },
    { label: "Compass", path: ICONS.creator },
    { label: "Paper", path: ICONS.actionForm },
    { label: "Writable Book", path: ICONS.modalForm },
    { label: "Pickaxe", path: ICONS.edit },
    { label: "Barrier", path: ICONS.delete },
    { label: "Arrow", path: ICONS.back },
    { label: "Emerald", path: ICONS.confirm },
    { label: "Redstone Dust", path: ICONS.cancel },
    { label: "Gold Ingot", path: ICONS.shop },
    { label: "Diamond", path: ICONS.sellAll },
    { label: "Lead", path: ICONS.binding },
    { label: "Repeater", path: ICONS.command },
    { label: "Book", path: ICONS.menu },
    { label: "Map", path: ICONS.sidebar },
    { label: "Nether Star", path: ICONS.rank },
    { label: "Spyglass", path: ICONS.plot },
    { label: "Name Tag", path: ICONS.item },
    { label: "Feather", path: ICONS.utility },
];
export const ICON_DEV_OPTIONS = [
    ...WORKING_ICON_OPTIONS,
    { label: "Apple", path: "textures/items/apple" },
    { label: "Bread", path: "textures/items/bread" },
    { label: "Carrot", path: "textures/items/carrot" },
    { label: "Coal", path: "textures/items/coal" },
    { label: "Ender Pearl", path: "textures/items/ender_pearl" },
    { label: "Feather", path: "textures/items/feather" },
    { label: "Fishing Rod", path: "textures/items/fishing_hook" },
    { label: "Flint and Steel", path: "textures/items/flint_and_steel" },
    { label: "Ghast Tear", path: "textures/items/ghast_tear" },
    { label: "Iron Ingot", path: "textures/items/iron_ingot" },
    { label: "Lead", path: "textures/items/lead" },
    { label: "Magma Cream", path: "textures/items/magma_cream" },
    { label: "Name Tag", path: "textures/items/name_tag" },
    { label: "Nether Star", path: "textures/items/nether_star" },
    { label: "Prismarine Crystals", path: "textures/items/prismarine_crystals" },
    { label: "Rabbit Foot", path: "textures/items/rabbit_foot" },
    { label: "Shield", path: "textures/items/elytra" },
    { label: "Slime Ball", path: "textures/items/slimeball" },
    { label: "Snowball", path: "textures/items/snowball" },
    { label: "Spyglass", path: "textures/items/spyglass" },
    { label: "Sugar", path: "textures/items/sugar" },
    { label: "Sugar Cane", path: "textures/items/reeds" },
    { label: "Stick", path: "textures/items/stick" },
    { label: "Wooden Sword", path: "textures/items/wood_sword" },
    { label: "Diamond Sword", path: "textures/items/diamond_sword" },
];
export const WORKING_ICON_PATHS = new Set(WORKING_ICON_OPTIONS.filter((option) => option.path !== undefined).map((option) => option.path));
export function isWorkingIconPath(value) {
    return typeof value === "string" && WORKING_ICON_PATHS.has(value);
}
